# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#

development:
  adapter: postgresql
  database: development
  username: bweimer # replace this with your own user name
  password: X7gha5w4? # replace this with your own password
  host: localhost
  encoding: UTF8
  pool: 5
  timeout: 5000
